name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project source code
        uses: actions/checkout@v2

      - name: Build and release project binary
        uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: '1.17'
          project_path: weed
          binary_name: weed
          pre_command: export CGO_ENABLED=0 && export GODEBUG=http2client=0
          build_flags: -trimpath
          ldflags: -s -w -X github.com/seaweedfs/seaweedfs/weed/util.VERSION=${{github.ref_name}}
          sha256sum: true
          md5sum: false
